routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('student', 'App\Http\Controllers\StudentController');

Route::get('/index', 'App\Http\Controllers\StudentController@index')-> name('index');

Route::get('/create', 'App\Http\Controllers\StudentController@create')-> name('create');

/*Route::get('/delete/{id}', 'App\Http\Controllers\StudentController@delete')->name('delete');*/

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = student::all();
        return view("index",['students'=>$students]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $students=Student::all();
        return view("create", compact('students'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $student= new Student;
        $student->name=$request->name;
        $student->lastname=$request->lastname;
        $student->number=$request->number;
        $student->phone=$request->phone;
        $student->save();

        return redirect()->route('index');

    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Student $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Student $student
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student=Student::findOrFail($id);
        return view('edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Student $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $student= Student::findOrFail($id);
        $student->name=$request->name;
        $student->lastname=$request->lastname;
        $student->number=$request->number;
        $student->phone=$request->phone;
        $student->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Student $student
     * @return \Illuminate\Http\Response
     */

    public function delete($id){
/*        Student::find($id)->delete();
        return redirect()->route('index');*/

    }
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->route('articles.index')
            ->with('success','Kayıt başarıyla silindi.');
    }
}

resources/views/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Icons font CSS-->
    <link href="resources/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="resources/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="resources/https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="resources/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="resources/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="resources/css/main.css" rel="stylesheet" media="all">
</head>

<body>
<div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins">
    <div class="wrapper wrapper--w780">

        <div class="card card-3">
            <div class="card-heading"></div>
            <div class="card-body">
                <h2 class="title">Registration Info</h2>
                <form action="{{ route('student.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="input-group">
                        <input class="input--style-3" type="text" placeholder="Name" name="name">
                    </div>
                    <div class="input-group">
                        <input class="input--style-3" type="text" placeholder="LastName" name="lastname">
                        <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                    </div>
                 {{--   <div class="input-group">
                        <div class="rs-select2 js-select-simple select--no-search">
                            <select name="gender">
                                <option disabled="disabled" selected="selected">Gender</option>
                                <option>Male</option>
                                <option>Female</option>
                                <option>Other</option>
                            </select>
                            <div class="select-dropdown"></div>
                        </div>
                    </div>--}}
                    <div class="input-group">
                        <input class="input--style-3" type="number" placeholder="Number" name="number">
                    </div>
                    <div class="input-group">
                        <input class="input--style-3" type="text" placeholder="Phone" name="phone">
                    </div>
                    <div class="p-t-10">
                        <button class="btn btn--pill btn--green" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Jquery JS-->
<script src="resources/vendor/jquery/jquery.min.js"></script>
<!-- Vendor JS-->
<script src="resources/vendor/select2/select2.min.js"></script>
<script src="resources/vendor/datepicker/moment.min.js"></script>
<script src="resources/vendor/datepicker/daterangepicker.js"></script>

<!-- Main JS-->
<script src="resources/js/global.js"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

resources/views/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Icons font CSS-->


<body>
<div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins">
    <div class="wrapper wrapper--w780">

        <div class="card card-3">
            <div class="card-heading"></div>
            <div class="card-body">
                <h2 class="title">Registration Info</h2>
                <form action="{{ route('student.update', $student->id)}}" method="POST" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                    <div class="input-group">
                        <input class="input--style-3" type="text" placeholder="Name" value="{{$student->name}}" name="name">
                    </div>
                    <div class="input-group">
                        <input class="input--style-3" type="text" placeholder="LastName" value="{{$student->lastname}}" name="lastname">
                        <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar"></i>
                    </div>
                    {{--   <div class="input-group">
                           <div class="rs-select2 js-select-simple select--no-search">
                               <select name="gender">
                                   <option disabled="disabled" selected="selected">Gender</option>
                                   <option>Male</option>
                                   <option>Female</option>
                                   <option>Other</option>
                               </select>
                               <div class="select-dropdown"></div>
                           </div>
                       </div>--}}
                    <div class="input-group">
                        <input class="input--style-3" type="number" placeholder="Number" value="{{$student->number}}" name="number">
                    </div>
                    <div class="input-group">
                        <input class="input--style-3" type="text" placeholder="Phone" value="{{$student->phone}}"name="phone">
                    </div>
                    <div class="p-t-10">
                        <button class="btn btn--pill btn--green" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

resources/views/index.blade.php
{{--
@foreach($students as $student)
    <label>{{$student->name}}</label> <br>
    <label>{{$student->lastname}}</label><br>
    <label>{{$student->number}}</label><br>
    <label>{{$student->phone}}</label><br>
@endforeach
--}}
<div class="card shadow mb-4">
    <div cla="card-heade py-3"> Öğrenciler</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>LastName</th>
                    <th>Number</th>
                    <th>Phone</th>
                    <th>İşlemler</th>
                </tr>
                </thead>
                <tbody>
                @foreach($students as $student)

                    <tr>
                        <td> {{$student->name}}</td>
                        <td> {{$student->lastname}}</td>
                        <td> {{$student->number}}</td>
                        <td> {{$student->phone}}</td>


                        <td>
                            <a href="{{route('student.edit', $student->id)}}" class="btn btn-sm btn-primary">Düzenle</a>
                        </td>
                        <td>
                            <form  action="{{ route('student.destory', $student->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit"
                                   class="btn btn-sm btn-primary">Sil</button>
                            </form>
                        </td>
                    </tr>
                @endforeach

                </tbody>

            </table>
        </div>
    </div>
</div>